### ISSUE TITLE
Has this been compared with geta ？

### ISSUE THREAD

**Issue by zhangwenda0518** [unavailable-2374/Genome-Wide-Annotation-Pipeline#1]
Hello, author. Is there any difference between this annotation process and geta? （https://github.com/chenlianfu/geta）Have you made a comparison?
Do you suggest that I continue to run EVM to integrate this result, so what should its score be set relative to PASA's result?

**Comment by unavailable-2374** [comment]
Hello，GWAP pipeline is based on geta, I just made a little change to suit my purpose. The difference between them is GWAP strengthen the prediction module and more positive results have been tried to be integrated.

To be honest,  I don't think that you need to put this result integrate with EVM, because our gene model  are supported by evidence or by Pfam results.
